### ISSUE TITLE
Use electron for app

### ISSUE THREAD

**Issue by D1WK** [SimpleEdit/editor#14]
https://www.electronjs.org for compile

**Comment by thecoder876** [comment]
> https://www.electronjs.org for compile

I thought about it too, but SimpleEdit is hosted on a server.

**Comment by D1WK** [comment]
We can just paste the code into the app, as that's what electron is for

**Comment by D1WK** [comment]
Also it would be so cool

**Comment by thecoder876** [comment]
> We can just paste the code into the app, as that's what electron is for

@D1WK Well, I've installed it.

**Comment by D1WK** [comment]
Niceeeeeee

**Comment by D1WK** [comment]
When it's finished, make a repo for it

**Comment by thecoder876** [comment]
Merged into #21 and #23.
