### ISSUE TITLE
Repl.it doesn't display images properly

### ISSUE THREAD

**Issue by thecoder876** [SimpleEdit/editor#16]
For some reason, Repl.it doesn't display images properly:
![image](https://user-images.githubusercontent.com/76265544/105712035-37316980-5f11-11eb-9ebe-a3c7395b69b7.png)

**Comment by D1WK** [comment]
Because the logo does exist a file in the repl, so it displays a broken image.

**Comment by thecoder876** [comment]
> Because the logo does exist as a file in the repl, it displays a broken image.

@D1WK Is that a typo? If it is, then the file _does_ exist, and in the ``views`` folder.

**Comment by thecoder876** [comment]
> Try switching from repl.it to github, and make it so the URL goes here: simpleedit.github.io/app

@D1WK So should I use this? https://simpleedit.github.io/LOGO.png

**Comment by D1WK** [comment]
yes

**Comment by thecoder876** [comment]
> yes

@D1WK OK then.
