### ISSUE TITLE
Invite to gitbook

### ISSUE THREAD

**Issue by D1WK** [SimpleEdit/editor#18]
Invite me (d1wk is my gitbook username) to the gitbook docs. @thecoder876  this is a direct callout.

**Comment by thecoder876** [comment]
> Invite me (d1wk is my gitbook username) to the gitbook docs. @thecoder876 this is a direct callout.

@D1WK ok

**Comment by thecoder876** [comment]
> > Invite me (d1wk is my gitbook username) to the gitbook docs. @thecoder876 this is a direct callout.
> 
> @D1WK ok

Wait, it's link only. Here's the link: https://app.gitbook.com/invite/simpleedit?invite=-MRtriOkxmB-eegdzaVD
