### ISSUE TITLE
Issues and Canny

### ISSUE THREAD

**Issue by thecoder876** [SimpleEdit/editor#19]
Issues sent here will now be automatically be sent to [our Canny feedback portal](https://simpleedit.canny.io "Visit our Canny feedback portal"). We may also reply to issues through Canny.

**Comment by D1WK** [comment]
The future is  **NOW**

**Comment by thecoder876** [comment]
> The future is **NOW**

@AmpersandGD lol

**Comment by thecoder876** [comment]
Seems like this won't work.

**Comment by AmpersandGD** [comment]
wdym
