### ISSUE TITLE
SimpleEdit Desktop

### ISSUE THREAD

**Issue by thecoder876** [SimpleEdit/editor#21]
For the desktop app, I have decided to use [NW.js](https://nwjs.io). This is because unlike with Electron, all that is needed is to put the files into the folder.

**Comment by Touchcreator** [comment]
hmmmm ok

**Comment by AmpersandGD** [comment]
Does it require NW.js to be installed on the user's computer?

**Comment by AmpersandGD** [comment]
Alright!

**Comment by thecoder876** [comment]
This shouldn't be closed just yet - it still needs to be discussed.

**Comment by thecoder876** [comment]
Idk why, but I'm just too lazy to bring all the latest changes into the local version so I can make the desktop app.

**Comment by AmpersandGD** [comment]
> Idk why, but I'm just too lazy to bring all the latest changes into the local version so I can make the desktop app.


I can do it when I get my hands on my windows laptop

**Comment by AmpersandGD** [comment]
>Ampersand is amazing 


Why thank you
