### ISSUE TITLE
Bank Account

### ISSUE THREAD

**Issue by AmpersandGD** [SimpleEdit/editor#22]
Give a bank account for SimpleEdit, then set it up for sponsorship maybe

**Comment by thecoder876** [comment]
Closed and locked. This is confidential and should only be visible to the team.

**Comment by AmpersandGD** [comment]
> Closed and locked. This is confidential and should only be visible to the team. Should be discussed in Discord.


Might take  a while tho cause  i'm on a school computer so they blocked discord
